name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v4

    - name: Générer un tag basé sur le commit
      id: vars
      run: echo "TAG=${GITHUB_SHA::8}" >> $GITHUB_OUTPUT

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build de l'image Docker
      run: |
        docker build . \
          --file Dockerfile \
          --tag lucaspadnot/app-github:${{ steps.vars.outputs.TAG }}

    - name: Push de l'image Docker vers Docker Hub
      run: |
        docker push lucaspadnot/app-github:${{ steps.vars.outputs.TAG }}
